name: ie-bank-infra

on:
  workflow_dispatch:         # Manual trigger
  push:
    paths:
      - '!scripts/**'       # Exclude scripts directory from triggering

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: gringo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Lint Bicep code
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep

      # Upload Bicep build artifact
      - name: Upload Bicep build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-build
          path: ./main.bicep

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: Deploy to Development
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: |
            appServiceAPIAppName=${{ vars.APP_NAME }}   # Assuming APP_NAME is defined in your vars
            appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
            appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }}
            appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
            appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }}
            appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }}
            appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
            appServiceAPIEnvVarENV=${{ vars.ENV }}
            environmentType=development
          deploymentName: ${{ env.USER_ALIAS }}

  deploy-uat:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Download Bicep build artifact
      - name: Download Bicep build artifact
        uses: actions/download-artifact@v4
        with:
          name: bicep-build

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to UAT
      - name: Deploy to UAT
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./main.bicep
          parameters: |
            appServiceAPIAppName=${{ vars.APP_NAME }}   # Assuming APP_NAME is defined in your vars
            appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
            appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }}
            appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
            appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }}
            appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }}
            appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
            appServiceAPIEnvVarENV=${{ vars.ENV }}
            environmentType=uat
          deploymentName: ${{ env.USER_ALIAS }}-uat
