name: ie-bank-infra

on:
  workflow_dispatch:         # Manual trigger
  push:                     # Trigger on push
    paths:
      - '!scripts/**'
  pull_request:             # Trigger on pull request to main
    branches:
      - main                # Only for pull requests targeting the main branch

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: gringo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Lint Bicep code
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.event_name == 'pull_request' ? 'UAT' : 'Development' }}  # Set environment based on event

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: Deploy to Azure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ github.event_name == 'pull_request' ? env.RESOURCE_GROUP_UAT : env.RESOURCE_GROUP_DEV }}  # Select resource group based on event
          template: ./main.bicep
          parameters: |
            appServiceAPIEnvVarENV=${{ vars.ENV }}
            appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }}
            appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }}
            appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
            appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
            appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }}
            appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
          deploymentName: ${{ env.USER_ALIAS }}-${{ github.event_name == 'pull_request' ? 'uat' : 'dev' }}  # Append suffix based on event type
